# Generated by Django 2.2.4 on 2019-12-06 19:12

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_foro', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(max_length=3000)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=app.models.subir_archivo)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Foros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_usuario', models.CharField(max_length=20)),
                ('foto_perfil', models.ImageField(default='usuarios/perfiles/default/default.jpg', null=True, upload_to=app.models.subir_foto_perfil)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Comentarios')),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Foros')),
                ('usu_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usu_respuesta', to='app.Usuarios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.Usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='foros',
            name='tipo_foro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tipos_Foros'),
        ),
        migrations.AddField(
            model_name='foros',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Usuarios'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='foro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Foros'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuarios'),
        ),
    ]
