# Generated by Django 2.2.4 on 2019-12-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nom_usuario',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
