# Generated by Django 2.2.4 on 2019-12-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191206_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nom_usuario',
            field=models.CharField(max_length=20),
        ),
    ]
