# Generated by Django 2.2.4 on 2019-12-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191206_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foros',
            name='tipo_foro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Tipos_Foros'),
        ),
    ]
