# Generated by Django 2.2.4 on 2019-12-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191215_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaDatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=300)),
            ],
        ),
    ]
