# Generated by Django 3.0.1 on 2020-01-02 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tabladatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField()),
                ('direccion', models.CharField(max_length=300)),
                ('usuario_nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_nom', to='app.Usuarios')),
                ('usuario_notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_notif', to='app.Usuarios')),
            ],
        ),
        migrations.DeleteModel(
            name='TablaDatos',
        ),
    ]
