# Generated by Django 3.0.1 on 2020-01-09 06:04

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200102_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=app.models.subir_archivo_comentario),
        ),
    ]
