# Generated by Django 3.0.1 on 2020-01-09 18:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200109_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.subir_archivo_comentario),
        ),
    ]
